HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Controllers/ApartmentController.cs
using HouseRentalManagementSystem.IRepository;
using HouseRentalManagementSystem.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HouseRentalManagementSystem.Areas.User.Controllers
{
    [Authorize]
    public class ApartmentController : Controller
    {
        private readonly IApartmentRepository iApartmentRepository;
        private readonly IBuildingRepository iBuildingRepository;
        private readonly IApartmentTypeRepository iApartmentTypeRepository;
        private readonly IApartmentImageRepository iApartmentImageRepository;
        private readonly IWebHostEnvironment iWebHostEnvironment;
        private readonly IApartmentFacilityRepository iApartmentFacilityRepository;
        private readonly IApartmentWiseFacilityRepository iApartmentWiseFacilityRepository;
        public ApartmentController(IApartmentWiseFacilityRepository _iApartmentWiseFacilityRepository,IApartmentRepository _iApartmentRepository, IWebHostEnvironment _iWebHostEnvironment, IBuildingRepository _iBuildingRepository, IApartmentTypeRepository _iApartmentTypeRepository, IApartmentImageRepository _iApartmentImageRepository, IApartmentFacilityRepository _iApartmentFacilityRepository)
        {
            iWebHostEnvironment = _iWebHostEnvironment;
            iApartmentRepository = _iApartmentRepository;
            iBuildingRepository = _iBuildingRepository;
            iApartmentTypeRepository = _iApartmentTypeRepository;
            iApartmentImageRepository = _iApartmentImageRepository;
            iApartmentFacilityRepository = _iApartmentFacilityRepository;
            iApartmentWiseFacilityRepository = _iApartmentWiseFacilityRepository;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            ViewBag.Building = iBuildingRepository.GetAll();
            ViewBag.Types = iApartmentTypeRepository.GetAll();
            ViewBag.Facilities = iApartmentFacilityRepository.GetAll();
            IEnumerable<ApartmentViewModel> itemList = iApartmentRepository.GetAll();
            int indexNumber = 0;
            foreach (var item in itemList)
            {
                item.SirialNumber = indexNumber += 1;

            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                itemList = itemList.Where(e => e.BuildingShortName.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    itemList = itemList.OrderByDescending(e => e.SirialNumber).ToList();
                    break;
                default:
                    itemList = itemList.OrderBy(e => e.SirialNumber).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(itemList.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public IActionResult Create(ApartmentViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.AptId > 0)
                {
                    ViewBag.ErrorMessage = "Apartment is not Added"; 
                    return RedirectToAction("Message", "Error", new { area = "" });
                }
                else
                {
                    ApartmentViewModel returnObj = iApartmentRepository.Insert(objModel);
                    ApartmentImageViewModel imageObj = new ApartmentImageViewModel();
                    ApartmentWiseFacilityViewModel facilityObj = new ApartmentWiseFacilityViewModel();
                    if (objModel.Photos != null && objModel.Photos.Count > 0)
                    {
                        foreach (IFormFile photo in objModel.Photos)
                        {
                            string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/apartment_images");
                            uniqueImageName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                            string filePath = Path.Combine(uploadFolder, uniqueImageName);
                            FileStream fileStream = new FileStream(filePath, FileMode.Create);
                            photo.CopyTo(fileStream);
                            fileStream.Close();
                            imageObj.AptId = returnObj.AptId;
                            imageObj.ImageName = uniqueImageName;
                            iApartmentImageRepository.Insert(imageObj);
                        }
                    }
                    if (objModel.FacilityCode != null && objModel.FacilityCode.Length > 0)
                    {
                        var Facilities = iApartmentFacilityRepository.GetAll();
                        foreach (ApartmentFacilityViewModel fac in Facilities)
                        {
                            int fac_val = fac.FacilityCode;
                            int k = 0;
                            for (int j = 0; j < objModel.FacilityCode.Length; j++)
                            {
                                int selected_fac_val = objModel.FacilityCode[j];
                                if (fac_val== selected_fac_val)
                                {
                                    k = 1;
                                }
                            }
                            if(k==0)
                            {
                                facilityObj.AptId = returnObj.AptId;
                                facilityObj.FacilityCode = fac.FacilityCode;
                                facilityObj.IsChecked = false;
                                iApartmentWiseFacilityRepository.Insert(facilityObj);
                            } else if(k==1)
                            {

                                facilityObj.AptId = returnObj.AptId;
                                facilityObj.FacilityCode = fac.FacilityCode;
                                facilityObj.IsChecked = true;
                                iApartmentWiseFacilityRepository.Insert(facilityObj);
                            }
                        }
                    }
                    result = true;
                }
            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Appartment is not save"; 
                return RedirectToAction("Message", "Error", new { area = "" });
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Building = iBuildingRepository.GetAll();
            ViewBag.Types = iApartmentTypeRepository.GetAll();
            ViewBag.Images = iApartmentImageRepository.GetAllByApartmentId(id);
            ViewBag.Facilities = iApartmentWiseFacilityRepository.GetAllByApartmentId(id);
            ApartmentViewModel obj = iApartmentRepository.GetById(id);
            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(ApartmentViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.AptId > 0)
                {
                    ApartmentViewModel returnObj = iApartmentRepository.Update(objModel);
                    ApartmentImageViewModel imageObj = new ApartmentImageViewModel();
                    ApartmentWiseFacilityViewModel facilityObj = new ApartmentWiseFacilityViewModel();
                    if (objModel.Edit_Photos != null && objModel.Edit_Photos.Count > 0)
                    {
                        foreach (IFormFile photo in objModel.Edit_Photos)
                        {
                            string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/apartment_images");
                            uniqueImageName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                            string filePath = Path.Combine(uploadFolder, uniqueImageName);
                            FileStream fileStream = new FileStream(filePath, FileMode.Create);
                            photo.CopyTo(fileStream);
                            fileStream.Close();
                            imageObj.AptId = returnObj.AptId;
                            imageObj.ImageName = uniqueImageName;
                            iApartmentImageRepository.Insert(imageObj);
                        }
                    }

                    if (objModel.FacilityCode != null && objModel.FacilityCode.Length > 0)
                    {
                        var facilitiesByApartmentId = iApartmentWiseFacilityRepository.GetAllByApartmentId(returnObj.AptId);
                        foreach (var apartmentWiseFacility in facilitiesByApartmentId)
                        {
                            iApartmentWiseFacilityRepository.Delete(apartmentWiseFacility.ApartmentWiseFacilityId);
                        }
                        var Facilities = iApartmentFacilityRepository.GetAll();
                        foreach (ApartmentFacilityViewModel fac in Facilities)
                        {
                            int fac_val = fac.FacilityCode;
                            int k = 0;

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/Apartment/Edit.cshtml
@model ApartmentViewModel
@{
    ViewData["Title"] = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-6 mx-auto">
    <div class="pl-0 d-inline-block">
        <div><span class="page_header">Update Apartment</span></div>
        <div style="padding-left:0">
        </div>
    </div>
    <form enctype="multipart/form-data" asp-action="Edit" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="AptId" />
        <div class="form-group mb-3">
            <label asp-for="BuildingShortName" class="form-label"></label>
            @if (ViewBag.Building != null)
            {
                <select asp-for="BuildingId" class="form-control" asp-items="@(new SelectList(@ViewBag.Building,"BuildingId", "BuildingShortName"))">
                    <option value="">--Select Building Name--</option>
                </select>
            }
            <span asp-validation-for="BuildingId" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="AptTypeCode" class="form-label"></label>
            @if (ViewBag.Types != null)
            {
                <select asp-for="AptTypeCode" class="form-control" asp-items="@(new SelectList(@ViewBag.Types,"AptTypeCode", "AptTypeDescription"))">
                    <option value="">--Select Apartment Type--</option>
                </select>
            }
            <span asp-validation-for="AptTypeCode" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="ApartmentName" class="form-label"></label>
            <input asp-for="ApartmentName" class="form-control" />
            <span asp-validation-for="ApartmentName" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Apartment Facility</label>
            <div class="card">
                <ul class="ks-cboxtags">
                    @if (ViewBag.Facilities != null)
                    {
                        @foreach (var item in ViewBag.Facilities)
                        {
                            <li>
                                <input type="checkbox" id="@item.FacilityCode" value="@item.FacilityCode" name="FacilityCode" checked="@item.IsChecked">
                                <label for="@item.FacilityCode">@item.FacilityDescription</label>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
        <div class="form-group position-relative mb-3">
            <label asp-for="BathroomCount" class="form-label"></label>
            <input asp-for="BathroomCount" class="form-control" />
            <span asp-validation-for="BathroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="BedroomCount" class="form-label"></label>
            <input asp-for="BedroomCount" class="form-control" />
            <span asp-validation-for="BedroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="RoomCount" class="form-label"></label>
            <input asp-for="RoomCount" class="form-control" />
            <span asp-validation-for="RoomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="MonthlyRent" class="form-label"></label>
            <input asp-for="MonthlyRent" class="form-control" />
            <span asp-validation-for="MonthlyRent" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="SecurityDepositAmount" class="form-label"></label>
            <input asp-for="SecurityDepositAmount" class="form-control" />
            <span asp-validation-for="SecurityDepositAmount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="OtherApartmentDetails" class="form-label"></label>
            <textarea asp-for="OtherApartmentDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
            <span asp-validation-for="OtherApartmentDetails" class="text-danger"></span>
        </div>
        @*<partial name="~/Areas/User/Views/Apartment/_Apartment_Images.cshtml" />*@
        <div class="form-group mb-3">
            <label asp-for="ImageName" class="form-label mb-3"></label>
            <div class="d-flex flex-wrap justify-content-start">
                @foreach (var image in ViewBag.Images)
                {
                    <div class="image_container d-flex justify-content-center position-relative">
                        <img src="./../../../images/apartment_images/@image.ImageName" alt="Image">
                        <a class="position-absolute btn_delete_images" asp-area="User" asp-controller="Apartment" asp-action="DeleteImage" asp-route-id="@image.ImageId" onclick="return confirm('Are you sure to delete?')">&times;</a>
                    </div>
                }
            </div>
        </div>
        <div class="form-group mb-3">
            <div class="d-flex flex-wrap justify-content-start" id="edit_container">
            </div>
            <input type="file" asp-for="Edit_Photos" multiple="" class="d-none" onchange="image_select()">
            <button class="btn btn_modal_close" type="button" onclick="document.getElementById('Edit_Photos').click()">Choose Images</button>
        </div>
        <div class="form-group mb-3">
            <input type="submit" value="Update" class="btn btn_modal" />
            <a asp-action="Index" class="btn btn_modal_close">Back To List</a>
        </div>
    </form>
</div>
<!--<div class="col-md-6 mx-auto">
    <div class="pl-0 d-inline-block">
        <div><span class="page_header">Update Apartment</span></div>
        <div style="padding-left:0">
        </div>
    </div>
    <form enctype="multipart/form-data" asp-action="Edit" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="AptId" />
        <div class="form-group mb-3">
            <label asp-for="BuildingShortName" class="form-label"></label>
            @if (ViewBag.Building != null)
            {
                <select asp-for="BuildingId" class="form-control" asp-items="@(new SelectList(@ViewBag.Building,"BuildingId", "BuildingShortName"))">
                    <option value="">--Select Building Name--</option>
                </select>
            }
            <span asp-validation-for="BuildingId" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="AptTypeCode" class="form-label"></label>
            @if (ViewBag.Types != null)
            {
                <select asp-for="AptTypeCode" class="form-control" asp-items="@(new SelectList(@ViewBag.Types,"AptTypeCode", "AptTypeDescription"))">
                    <option value="">--Select Apartment Type--</option>
                </select>
            }
            <span asp-validation-for="AptTypeCode" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="ApartmentName" class="form-label"></label>
            <input asp-for="ApartmentName" class="form-control" />
            <span asp-validation-for="ApartmentName" class="text-danger"></span>
        </div>
        <div class="form-group position-relative mb-3">
            <label asp-for="BathroomCount" class="form-label"></label>
            <input asp-for="BathroomCount" class="form-control" />
            <span asp-validation-for="BathroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="BedroomCount" class="form-label"></label>
            <input asp-for="BedroomCount" class="form-control" />
            <span asp-validation-for="BedroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="RoomCount" class="form-label"></label>
            <input asp-for="RoomCount" class="form-control" />
            <span asp-validation-for="RoomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="MonthlyRent" class="form-label"></label>
            <input asp-for="MonthlyRent" class="form-control" />
            <span asp-validation-for="MonthlyRent" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="SecurityDepositAmount" class="form-label"></label>
            <input asp-for="SecurityDepositAmount" class="form-control" />
            <span asp-validation-for="SecurityDepositAmount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="OtherApartmentDetails" class="form-label"></label>
            <textarea asp-for="OtherApartmentDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
            <span asp-validation-for="OtherApartmentDetails" class="text-danger"></span>
        </div>-->
@*<partial name="~/Areas/User/Views/Apartment/_Apartment_Images.cshtml" />*@
<!--<div class="form-group mb-3">
            <label asp-for="ImageName" class="form-label mb-3"></label>
            <div class="d-flex flex-wrap justify-content-start">
                @foreach (var image in ViewBag.Images)
                {
                    <div class="image_container d-flex justify-content-center position-relative">
                        <img src="./../../../images/apartment_images/@image.ImageName" alt="Image">
                        <a class="position-absolute btn_delete_images" asp-area="User" asp-controller="Apartment" asp-action="DeleteImage" asp-route-id="@image.ImageId" onclick='confirmation()'>&times;</a>
                    </div>
                }
            </div>
        </div>
        <div class="form-group mb-3">
            <div class="d-flex flex-wrap justify-content-start" id="edit_container">
            </div>
            <input type="file" asp-for="Edit_Photos" multiple="" class="d-none" onchange="image_select()">
            <button class="btn btn_modal_close" type="button" onclick="document.getElementById('Edit_Photos').click()">Choose Images</button>
        </div>
        <div class="form-group mb-3">
            <input type="submit" value="Update" class="btn btn_modal" />
            <a asp-action="Index" class="btn btn_modal_close">Back To List</a>
        </div>
    </form>
</div>-->
<script>

    var images = [];
    // this function will select images
    function image_select() {
        var image = document.getElementById('Edit_Photos').files;
        for (i = 0; i < image.length; i++) {
            if (check_duplicate(image[i].name)) {
                images.push({
                    "name": image[i].name,
                    "url": URL.createObjectURL(image[i]),
                    "file": image[i],
                })
            } else {
                alert(image[i].name + " is already added to the list");
            }
        }

        /*document.getElementById('form').reset();*/
        document.getElementById('edit_container').innerHTML = image_show();
    }
    // this function will show images in the DOM
    function image_show() {
        var image = "";
        images.forEach((i) => {
            image += `<div class="image_container d-flex justify-content-center position-relative">
                   <img src="`+ i.url + `" alt="Image">
                   <span class="position-absolute" onclick="delete_image(`+ images.indexOf(i) + `)">&times;</span>
              </div>`;
        })
        return image;
    }

    // this function will get all images from the array
    function get_image_data() {
        var form = new FormData()
        for (let index = 0; index < images.length; index++) {
            form.append("file[" + index + "]", images[index]['file']);
        }
        return form;
    }

    // this function will delete a specific image from the container
    function delete_image(index) {
        var attachments = document.getElementById('Edit_Photos').files;
        var fileBuffer = new DataTransfer();

        // append the file list to an array iteratively
        for (let i = 0; i < attachments.length; i++) {
            // Exclude file in specified index
            if (index !== i)
                fileBuffer.items.add(attachments[i]);
        }

        // Assign buffer to file input
        document.getElementById("Edit_Photos").files = fileBuffer.files;

        images.splice(index, 1);
        document.getElementById('edit_container').innerHTML = image_show();
    }

    // this function will check duplicate images
    function check_duplicate(name) {
        var image = true;
        if (images.length > 0) {
            for (e = 0; e < images.length; e++) {
                if (images[e].name == name) {
                    image = false;
                    break;
                }
            }
        }
        return image;
    }
</script>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/Apartment/_Create.cshtml
@model ApartmentViewModel
<form enctype="multipart/form-data" asp-action="Create" method="post" id="form">
    <div class="col-md-12 mx-auto">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group mb-3">
            <label asp-for="BuildingShortName" class="form-label"></label>
            @if (ViewBag.Building != null)
            {
                <select asp-for="BuildingId" class="form-control" asp-items="@(new SelectList(@ViewBag.Building,"BuildingId", "BuildingShortName"))">
                    <option value="">Select...</option>
                </select>
            }
            <span asp-validation-for="BuildingId" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="AptTypeCode" class="form-label"></label>
            @if (ViewBag.Types != null)
            {
                <select asp-for="AptTypeCode" class="form-control" asp-items="@(new SelectList(@ViewBag.Types,"AptTypeCode", "AptTypeDescription"))">
                    <option value="">Select...</option>
                </select>
            }
            <span asp-validation-for="AptTypeCode" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="ApartmentName" class="form-label"></label>
            <input asp-for="ApartmentName" class="form-control" />
            <span asp-validation-for="ApartmentName" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label">Apartment Facility</label>
            <div class="card">
                <ul class="ks-cboxtags">
                    @if (ViewBag.Facilities != null)
                    {
                        @foreach (var item in ViewBag.Facilities)
                        {
                            <li>
                                <input type="checkbox" id="@item.FacilityCode" value="@item.FacilityCode" name="FacilityCode">
                                <label for="@item.FacilityCode">@item.FacilityDescription</label>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
        <div class="form-group mb-3">
            <label asp-for="BathroomCount" class="form-label"></label>
            <input type="text" asp-for="BathroomCount" class="form-control" />
            <span asp-validation-for="BathroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="BedroomCount" class="form-label"></label>
            <input type="text" asp-for="BedroomCount" class="form-control" />
            <span asp-validation-for="BedroomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="RoomCount" class="form-label"></label>
            <input type="text" asp-for="RoomCount" class="form-control" />
            <span asp-validation-for="RoomCount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="MonthlyRent" class="form-label"></label>
            <input asp-for="MonthlyRent" class="form-control" />
            <span asp-validation-for="MonthlyRent" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="SecurityDepositAmount" class="form-label"></label>
            <input asp-for="SecurityDepositAmount" class="form-control" />
            <span asp-validation-for="SecurityDepositAmount" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="OtherApartmentDetails" class="form-label"></label>
            <textarea asp-for="OtherApartmentDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
            <span asp-validation-for="OtherApartmentDetails" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <div class="d-flex flex-wrap justify-content-start" id="container">
            </div>
            <input type="file" asp-for="Photos" multiple="" class="d-none" onchange="image_select()">
            <button class="btn btn_modal_close" type="button" onclick="document.getElementById('Photos').click()">Choose Images</button>
        </div>
        <div class="form-group mb-3">
            <input type="submit" value="Create" class="btn btn_modal" />
            <input type="button" value="Close" data-bs-dismiss="modal" class="btn btn_modal_close" />
        </div>
    </div>
</form>
<script>

    var images = [];
    // this function will select images
    function image_select() {
        var image = document.getElementById('Photos').files;
        for (i = 0; i < image.length; i++) {
            if (check_duplicate(image[i].name)) {
                images.push({
                    "name": image[i].name,
                    "url": URL.createObjectURL(image[i]),
                    "file": image[i],
                })
            } else {
                alert(image[i].name + " is already added to the list");
            }
        }

        //document.getElementById('form').reset();
        document.getElementById('container').innerHTML = image_show();
    }
    // this function will show images in the DOM
    function image_show() {
        var image = "";
        images.forEach((i) => {
            image += `<div class="image_container d-flex justify-content-center position-relative">
                   <img src="`+ i.url + `" alt="Image">
                   <span class="position-absolute" onclick="delete_image(`+ images.indexOf(i) + `)">&times;</span>
              </div>`;
        })
        return image;
    }

    // this function will get all images from the array
    function get_image_data() {
        var form = new FormData()
        for (let index = 0; index < images.length; index++) {
            form.append("file[" + index + "]", images[index]['file']);
        }
        return form;
    }

    // this function will delete a specific image from the container
    function delete_image(index) {
        var attachments = document.getElementById('Photos').files;
        var fileBuffer = new DataTransfer();

        // append the file list to an array iteratively
        for (let i = 0; i < attachments.length; i++) {
            // Exclude file in specified index
            if (index !== i)
                fileBuffer.items.add(attachments[i]);
        }

        // Assign buffer to file input
        document.getElementById("Photos").files = fileBuffer.files;

        images.splice(index, 1);
        document.getElementById('container').innerHTML = image_show();
    }

    // this function will check duplicate images
    function check_duplicate(name) {
        var image = true;
        if (images.length > 0) {
            for (e = 0; e < images.length; e++) {
                if (images[e].name == name) {
                    image = false;
                    break;
                }
            }
        }
        return image;
    }
</script>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/Apartment/_ViewImages.cshtml
@model IEnumerable<ApartmentImageViewModel>
<div class="form-group mb-3">
    <div class="d-flex flex-wrap justify-content-start">
        @foreach (var image in Model)
        {<div class="image_container d-flex justify-content-center position-relative">
                <img src="./../../../images/apartment_images/@image.ImageName" alt="Image">
            </div>
        }
    </div>
</div>
<div class="form-group mb-3">
    <input type="button" value="Close" data-bs-dismiss="modal" class="btn btn_modal_close" />
</div>