HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Controllers/ApartmentBuildingController.cs
using HouseRentalManagementSystem.IRepository;
using HouseRentalManagementSystem.UserViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HouseRentalManagementSystem.Controllers
{
    [Authorize]
    public class ApartmentBuildingController : Controller
    {
        private readonly IBuildingRepository iBuildingRepository;
        private readonly IWebHostEnvironment iWebHostEnvironment;
        public ApartmentBuildingController(IBuildingRepository _iBuildingRepository, IWebHostEnvironment _iWebHostEnvironment)
        {
            iWebHostEnvironment = _iWebHostEnvironment;
            iBuildingRepository = _iBuildingRepository;
        }
        public IActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if(SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            IEnumerable<ApartmentBuildingViewModel> itemList = iBuildingRepository.GetAll();
            int indexNumber = 0;
            foreach (var item in itemList)
            {
               item.SirialNumber = indexNumber += 1;

            }
            if(!string.IsNullOrEmpty(SearchString))
            {
                itemList = itemList.Where(e => e.BuildingShortName.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    itemList = itemList.OrderByDescending(e => e.SirialNumber).ToList();
                    break;
                default:
                    itemList = itemList.OrderBy(e => e.SirialNumber).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(itemList.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApartmentBuildingViewModelMultipleInsert objModel, IFormFile[] ImageName)
        {
            if (ModelState.IsValid)
            {
                string uniqueImageName = null;
                if (ImageName != null)
                {
                    if (objModel.ApartmentBuildingViewModels.Count == ImageName.Count())
                    {
                        for (int i = 0; i < objModel.ApartmentBuildingViewModels.Count; i++)
                        {
                            if (ImageName[i] != null)
                            {
                                string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/building_images");
                                uniqueImageName = Guid.NewGuid().ToString() + "_" + ImageName[i].FileName;
                                string filePath = Path.Combine(uploadFolder, uniqueImageName); 
                                FileStream fileStream = new FileStream(filePath, FileMode.Create);
                                ImageName[i].CopyTo(fileStream);
                                fileStream.Close();
                                objModel.ApartmentBuildingViewModels[i].ImageName = uniqueImageName;
                                iBuildingRepository.Insert(objModel.ApartmentBuildingViewModels[i]);
                            }

                        }
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrorMessage = "Building  is not Added";
                return RedirectToAction("Message", "Error", new { area = "" });
            }

        }
        [HttpGet]
        public PartialViewResult Edit(int id)
        {
            ApartmentBuildingViewModel obj = iBuildingRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Areas/User/Views/ApartmentBuilding/_Edit.cshtml", obj);
        }
        //public IActionResult Edit(int id)
        //{
        //    ViewBag.Details = "Show";
        //    ApartmentBuildingViewModel building = iBuildingRepository.GetById(id);
        //    return View(building);
        //}
        [HttpPost]
        public IActionResult Edit(ApartmentBuildingViewModel objModel)
        {
            string uniqueImageName = null;
            bool result = false;
            if (ModelState.IsValid)
            {
                if (objModel.BuildingId > 0)
                {
                    if (objModel.Photo != null)
                    {
                        string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/building_images");
                        DeleteExistingImage(Path.Combine(uploadFolder, objModel.ImageName));
                        uniqueImageName = Guid.NewGuid().ToString() + "_" + objModel.Photo.FileName;
                        string filePath = Path.Combine(uploadFolder, uniqueImageName);
                        FileStream fileStream = new FileStream(filePath, FileMode.Create);
                        objModel.Photo.CopyTo(fileStream);
                        fileStream.Close();
                        objModel.ImageName = uniqueImageName;
                    }
                    iBuildingRepository.Update(objModel);
                    result = true;
                }
            }

            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ApartmentBuildingViewModel building = iBuildingRepository.GetById(objModel.BuildingId);
                return View(building);
            }
        }

        [HttpGet]
        public PartialViewResult Details(int id)
        {
            ApartmentBuildingViewModel obj = iBuildingRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Areas/User/Views/ApartmentBuilding/_Details.cshtml", obj);
        }
        public PartialViewResult ShowImage(int id)
        {
            ApartmentBuildingViewModel obj = iBuildingRepository.GetById(id);
            ViewBag.Details = "Show";
            return PartialView("~/Areas/User/Views/ApartmentBuilding/_ShowImage.cshtml", obj);
        }
        
        public IActionResult Delete(int id)
        {
            var building = iBuildingRepository.GetById(id);
            if (building.ImageName != null)
            {
                string uploadFolder = Path.Combine(iWebHostEnvironment.WebRootPath, "images/building_images");
                DeleteExistingImage(Path.Combine(uploadFolder, building.ImageName));
            }
            iBuildingRepository.Delete(building.BuildingId);
            return RedirectToAction("Index");
        }
        private void DeleteExistingImage(string imagePath)
        {
            FileInfo fileObj = new FileInfo(imagePath);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }
    }
}

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBuilding/Index.cshtml
@model IEnumerable<ApartmentBuildingViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div class="pl-0">
        <div><span class="page_header">Building</span></div>
        <div style="padding-left:0">
            <button type="button" class="btn_add_new" data-bs-toggle="modal" data-bs-target="#CreateModal">Create New</button>
        </div>
    </div>
    <table class="table table-bordered table-striped list_table">
        <thead>
            <tr>
                <th class="text-center">
                    @Html.ActionLink("###", "Index", new { SortOrder = ViewBag.SortNameParam }, new { @class = "text-decoration-none text-white" })
                </th>
                <th>
                    Building Short Name
                </th>
                <th>
                    Building Full Name
                </th>
                <th class="tbl_large_field">
                    Building Description
                </th>
                <th>
                    Building Address
                </th>
                <th>
                    Building Manager
                </th>
                <th class="text-center">
                    Building Phone
                </th>
                <th class="tbl_large_field">
                    Other Building Details
                </th>
                <th class="text-center">
                    Building Image
                </th>
                <th class="text-center tbl_action">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @item.SirialNumber
                    </td>
                    <td>
                        @item.BuildingShortName
                    </td>
                    <td>
                        @item.BuildingFullName
                    </td>
                    <td class="tbl_large_field">
                        @item.BuildingDescription
                    </td>
                    <td>
                        @item.BuildingAddress
                    </td>
                    <td>
                        @item.BuildingManager
                    </td>
                    <td class="text-center">
                        @item.BuildingPhone
                    </td>
                    <td class="tbl_large_field">
                        @item.OtherBuildingDetails
                    </td>
                    <td class="text-center">
                        <a class="btn_view_images" onclick='ShowImage(@item.BuildingId)' data-bs-toggle="modal" data-bs-target="#ViewImagesModal">View&nbsp;Images</a>
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <div class="dropdown">
                                <a class="btn_table dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item" onclick='Update(@item.BuildingId)' data-bs-toggle="modal" data-bs-target="#EditModal">Edit</a></li>
                                    <li><a class="dropdown-item" asp-area="User" asp-controller="ApartmentBuilding" asp-action="Delete" asp-route-id="@item.BuildingId" onclick="return confirm('Are you sure to delete?')">Delete</a></li>
                                    <li><a class="dropdown-item" onclick='Details(@item.BuildingId)' data-bs-toggle="modal" data-bs-target="#DetailsModal">Details</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <div class="search_section">
        <form asp-action="Index" method="get">
            <div>
                <span class="search_title">Find By Short Name: </span>
                <input type="text" class="input_search" name="SearchString" value="@ViewBag.CurrentFilter" />
                <input type="submit" value="Search" class="btn_search" />
                <a asp-action="Index" class="btn_back_to_list">Back to List</a>
            </div>
        </form>
    </div>
    <div class="page_section">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
        ContainerDivClasses = new[] { "navication" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
    })
    </div>
</div>
<div id="itemsDiv">
</div>
<div class="modal fade" id="CreateModal" tabindex="-1" aria-labelledby="CreateModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            @await Html.PartialAsync("_Create", new ApartmentBuildingViewModelMultipleInsert())
        </div>
    </div>
</div>
<div class="modal fade" id="EditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5">
                <h3 class="modal-title" id="detailsModalLabel">Update Building</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="EditDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBuilding/_Edit.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="DetailsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5 ba">
                <h3 class="modal-title" id="detailsModalLabel">Building Details</h3>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="DetailsDiv">
                    @if (ViewBag.Details == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBuilding/_Details.cshtml" />
                        ViewBag.Details = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ViewImagesModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header px-md-5 ba">
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-md-5">
                <div id="ViewImagesDiv">
                    @if (ViewBag.ViewImages == "Show")
                    {
                        <partial name="~/Areas/User/Views/ApartmentBuilding/_ViewImages.cshtml" />
                        ViewBag.ViewImages = "";
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
        if (isNaN(@TempData["id"]) == false) {
            var link = '@Url.Action("GetCategoryWiseItems", "Categories", new { id = @TempData["id"] })';
            $("#itemsDiv").load(link);
        }
        $('#CreateModal').on('shown.bs.modal', function () {
            $('#Name').trigger('focus');
        });
        $('#CreateModal').on('hidden.bs.modal', function (event) {
            $("input[type=text]").val("");
            $("input[type=number]").val("");
            $("input[type=datetime-local]").val("");
            $('#sl').val('0');

            $("img[data-tag='Image']").each(function () {
                $(this).attr("src", "/images/no-image.png");
            });
            $("div").each(function () {
                if (parseInt(this.id) > 0) {
                    this.remove();
                }
            })
        });
        $('#addModelButton').on('click', function () {
            var present_sl = parseInt($('#sl').val());
            var next_sl = parseInt(present_sl) + 1;
            var next_item = '<div id="' + next_sl + '">' + $('#' + present_sl).html() + '</div>';
            next_item = next_item.split('_' + present_sl.toString()).join('_' + next_sl.toString());
            next_item = next_item.split('[' + present_sl.toString() + ']').join('[' + next_sl.toString() + ']');
            $('#' + present_sl).after(next_item);
            $('#sl').val(next_sl);
        });

        $('#itemModal').on('hidden.bs.modal', function (event) {
            $("input[type=text]").val("");
            $("input[type=number]").val("");
            $("input[type=datetime-local]").val("");
            $("img[data-tag='Image']").each(function () {
                $(this).attr("src", "/images/no-image.png");
            });
        });
        });
        @*function editCategory(e) {
            var link = '@Url.Action("Edit", "Categories", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#editCategoryModalContent").load(link);
        }
        function deleteCategory(e) {
            var link = '@Url.Action("Delete", "Categories", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#deleteCategoryModalContent").load(link);
        }
        function getDetails(e) {
            var link = '@Url.Action("GetCategoryWiseItems", "Categories", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#itemsDiv").load(link);
        }
        function loadItem(e) {
            var link = '@Url.Action("Create", "Items", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#itemModalContent").load(link);
        }
        function editItem(e) {
            var link = '@Url.Action("Edit", "Items", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#editItemModalContent").load(link);
        }
        function deleteItem(e) {
            var link = '@Url.Action("Delete", "Items", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#deletItemModalContent").load(link);
        }*@

        function loadItem(e) {
            var link = '@Url.Action("Create", "ApartmentBuildingViewModels", new { id = "-1" })';
            link = link.replace("-1", e);
            $("#itemModalContent").load(link);
        }
        var loadImage = function (event) {
            if (event.target.files && event.target.files[0]) {
                var img = document.getElementById('Image');
                img.src = URL.createObjectURL(event.target.files[0]);
            }
        }
        var editImage = function (event) {
            if (event.target.files && event.target.files[0]) {
                var img = document.querySelector('img[alt = "Edit Image"]')
                img.src = URL.createObjectURL(event.target.files[0]);
            }
        }
        var changeImage = function (obj, event) {
            if (event.target.files && event.target.files[0]) {
                console.log(obj.dataset.tag);
                var img = document.getElementById(obj.dataset.tag);
                img.src = URL.createObjectURL(event.target.files[0]);
            }
        }

        function Update(id) {
            $.ajax({
                url: "/User/ApartmentBuilding/Edit?id=" + id,
                type: "GET",
                data: "",
                contentType: 'application/json; charset = utf-8',
                success: function (data) {
                    $('#EditDiv').show();
                    $('#EditDiv').html(data);
                },
                error: function () {
                    alert("Error occured")
                }
            })
        }
        function Details(id) {
            $.ajax({
                url: "/User/ApartmentBuilding/Details?id=" + id,
                type: "GET",
                data: "",
                contentType: 'application/json; charset = utf-8',
                success: function (data) {
                    $('#DetailsDiv').show();
                    $('#DetailsDiv').html(data);
                },
                error: function () {
                    alert("Error occured")
                }
            })
        }
        function ShowImage(id) {
            $.ajax({
                url: "/User/ApartmentBuilding/ShowImage?id=" + id,
                type: "GET",
                data: "",
                contentType: 'application/json; charset = utf-8',
                success: function (data) {
                    $('#ViewImagesDiv').show();
                    $('#ViewImagesDiv').html(data);
                },
                error: function () {
                    alert("Error occured")
                }
            })
        }
    </script>
}

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBuilding/_Create.cshtml
@model ApartmentBuildingViewModelMultipleInsert
<form enctype="multipart/form-data" asp-action="Create" method="post">
    <div class="modal-header">
        <h5 class="modal-title" id="categoryModalLabel">Add new category</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <div class="row" id="0">
            <div class="col-md-12 mx-auto">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingShortName" class="form-label"></label>
                    <input asp-for="ApartmentBuildingViewModels[0].BuildingShortName" class="form-control" />
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingShortName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingFullName" class="form-label"></label>
                    <input asp-for="ApartmentBuildingViewModels[0].BuildingFullName" class="form-control" />
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingFullName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingDescription" class="form-label"></label>
                    <textarea asp-for="ApartmentBuildingViewModels[0].BuildingDescription" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingDescription" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingAddress" class="form-label"></label>
                    <input asp-for="ApartmentBuildingViewModels[0].BuildingAddress" class="form-control" />
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingAddress" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingManager" class="form-label"></label>
                    <input asp-for="ApartmentBuildingViewModels[0].BuildingManager" class="form-control" />
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingManager" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].BuildingPhone" class="form-label"></label>
                    <input asp-for="ApartmentBuildingViewModels[0].BuildingPhone" class="form-control" />
                    <span asp-validation-for="ApartmentBuildingViewModels[0].BuildingPhone" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].OtherBuildingDetails" class="form-label"></label>
                    <textarea asp-for="ApartmentBuildingViewModels[0].OtherBuildingDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)"></textarea>
                    <span asp-validation-for="ApartmentBuildingViewModels[0].OtherBuildingDetails" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ApartmentBuildingViewModels[0].ImageName" class="form-label mb-3"></label>
                    <img id="_0" src="~/images/app_images/no-image.png" style="height:90px!important; width:auto!important;" class="form-control change_edit mb-3" asp-append-version="true" data-tag="Image" />
                    <input asp-for="ApartmentBuildingViewModels[0].ImageName" id="ImageName" name="ImageName" class="form-control change_image" type="file" data-tag="_0" onchange="changeImage(this, event)" required />
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <button id="addModelButton" type="button" class="btn btn_modal">Add more product</button>
        </div>
        <input id="sl" type="hidden" value="0" />
    </div>
    <div class="modal-footer">
        <div class="col-md-12">
            <input type="submit" value="Save" class="btn btn_modal" />
            <input type="button" value="Close" data-bs-dismiss="modal" class="btn btn_modal_close" />
        </div>
    </div>
</form>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBuilding/_Details.cshtml
@model ApartmentBuildingViewModel
@{
    var imagePath = "~/images/building_images/" + (Model.ImageName ?? "no-image.png");
}
<div class="row">
    <div class="col-md-12 mx-auto">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BuildingId" />
            <input type="hidden" asp-for="ImageName" />
            <div class="form-group mb-3">
                <label asp-for="BuildingShortName" class="form-label"></label>
                <input asp-for="BuildingShortName" class="form-control" readonly/>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BuildingFullName" class="form-label"></label>
                <input asp-for="BuildingFullName" class="form-control" readonly/>
            </div>
            <div class="form-group position-relative mb-3">
                <label asp-for="BuildingDescription" class="form-label"></label>
                <textarea asp-for="BuildingDescription" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)" readonly></textarea>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BuildingAddress" class="form-label"></label>
                <input asp-for="BuildingAddress" class="form-control" readonly/>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BuildingManager" class="form-label"></label>
                <input asp-for="BuildingManager" class="form-control" readonly/>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BuildingPhone" class="form-label"></label>
                <input asp-for="BuildingPhone" class="form-control" readonly/>
            </div>
            <div class="form-group mb-3">
                <label asp-for="OtherBuildingDetails" class="form-label"></label>
                <textarea asp-for="OtherBuildingDetails" class="form-control" text-wrap:normal" type="text" placeholder="Write here (Optional)" readonly></textarea>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Photo" class="form-label mb-3"></label>
                <img src="@imagePath" style="height: 90px !important; width: auto !important;" class="changeEdit form-control mb-3" asp-append-version="true" />
            </div>
            <div class="form-group mb-3">
                <input type="button" value="Close" data-bs-dismiss="modal" class="btn btn_modal_close" />
            </div>
        </form>
    </div>
</div>

HouseRentalManagementSystem5/HouseRentalManagementSystem/HouseRentalManagementSystem/Areas/User/Views/ApartmentBuilding/_ShowImage.cshtml
@model ApartmentBuildingViewModel
@{
    var imagePath = "~/images/building_images/" + (Model.ImageName ?? "no-image.png");
}
<div class="form-group mb-3">
    <label asp-for="Photo" class="form-label mb-3"></label>
    <img src="@imagePath" style="width:100%!important; height:auto!important;" class="form-control changeEdit mb-3" asp-append-version="true" />
</div>
<div class="form-group mb-3">
    <input type="button" value="Close" data-bs-dismiss="modal" class="btn btn_modal_close" />
</div>